project:
  type: website

website:
  title: "categories-bug"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/EllaKaye/categories-bug

format:
  html:
    theme: cosmo
    css: styles.css



